name: Generate Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: serral
          # BRANCH_NAME: main
          # UTC_OFFSET: 0
          # EXCLUDE: html,css
          # EXCLUDE_REPOS: some-repo,owner/other-repo
          THEME: github_dark
          # ANIMATION: fade
          # DURATION: 2
          # NAME: Andre Serralheiro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
